### PR TITLE
Front-end Development Update, commit 403018c

### PR DESCRIPTION
**Pull request by Ciezo**
Update into `src.com.jester.view`
Added assets directory into `src.com.jester.view.assets`

Please, see `docs/wireframe/UX.pdf`

View.java is staged.
 - A skeletal base GUI on the View layer is provided. 
 - Panels
 - Buttons 
 - Labels 
 - Custom images from `src.com.jester.view.assets.*png`
 - Working CardLayout
 - Anonymous Listeners 
 - Anonymous Event handling

assets directory is staged. 
- logo.png
- play.png
- playButton.png
- stop.png

Changes authored by @Ai-nihil , Ron

### CODE REVIEW

**Comment by Ciezo** [comment]
Waiting for review, then merge to main changes on the view level.

**Comment by Ai-nihil** [comment]
LGTM!

**Comment by Ciezo** [comment]
Review accepted!

**Comment by Ciezo** [comment]
Merge main <- front-end

**Pull request merged**
